### ISSUE TITLE
Remove Editor Specific Config i.e. .idea directory

### ISSUE THREAD

**Issue by rrajasek95** [saurabhima/gsoc_LEADERBOARD#1]
I noticed that there's a `.idea` directory present in the repository. That will cause issues if someone else happens to use IntelliJ/PyCharm for their project since it'll overwrite their config for the project, such as the virtualenv for example. Removing that ASAP would solve this issue. 

Also, adding a .gitignore entry for these config folders would be a good idea.

**Comment by rrajasek95** [comment]
I saw that you fixed it partially. I've added the complete fix in commit https://github.com/saurabhima/gsoc_LEADERBOARD/pull/3/commits/10160d61b4fe9323cdc9e2056e3f428a8e4ddb4e

We can close the issue after merging the PR

**Comment by saurabhima** [comment]
I have merged the Code.Thanks for the help
