### ISSUE TITLE
register_new_donor integrity violation?

### ISSUE THREAD

**Issue by rrajasek95** [saurabhima/gsoc_LEADERBOARD#2]
I noticed in the `subprocess.py` file that the `register_new_donor` function adds a new entry with the `volunteer_name` field as `None`. Since you've defined volunteer_name as `NOT NULL` in the `models.py`, this prevents a user from being added.

I can fix this and add a pull request, but I'd like to know what to do in this case. Should I make `volunteer_name` nullable or  should I add an extra field in the form for volunteer name?

**Comment by saurabhima** [comment]
I have changed the data model in models.py to allow Null Entry
